### ISSUE TITLE
Thank you for the great tutorial

### ISSUE THREAD

**Issue by saurabhnanda** [nomicflux/servant-opaleye-blog#2]
(didn't know how else to leave feedback).

Btw, any chance of updating it to use connection pooling and file-based logging (either request/response logging, or app-level logging)?

**Comment by nomicflux** [comment]
Thanks saurabhnanda!  I'm definitely planning on adding those things - life's gotten hectic, but those are on tap for the next couple of lessons.

**Comment by nomicflux** [comment]
Connection pooling added.  Hopefully file-based logging will be here in a week or so.
